import LangUtil from "@/core/global/LangUtil";
import i18n from "@/lang";
/**弹窗状态 */
export var DialogStatus = {
    create: "create",
    update: "update",
};
/**操作成功显示的消息 */
export var SuccessMessage = {
    create: <any>LangUtil("新增成功"),
    update: <any>LangUtil("编辑成功"),
};

/**客户端对应的跳转明 */
export var ClientModuleUrl = [
    { sort: 1, name: "推广页面", value: "openpage_extension" },
    { sort: 1, name: "币种介绍", value: "openpage_introduce" },
    { sort: 1, name: "首页", value: "openpage_home" },
    { sort: 1, name: "游戏列表", value: "openpage_gamelist" },
    { sort: 1, name: "质押分红", value: "openpage_bonus" },
    { sort: 1, name: "信用统计", value: "openpage_statist_credit" },
    { sort: 1, name: "easybet体育", value: "openpage_soccer" },
    { sort: 1, name: "板球", value: "openpage_soccer_cricket" },
    { sort: 1, name: "游戏返水", value: "openpage_mine" },
    { sort: 1, name: "swap交易", value: "openpage_swap" },
    { sort: 1, name: "我的", value: "openpage_my_info" },
    { sort: 1, name: "充值", value: "openpage_recharge" },
    { sort: 1, name: "登录", value: "openpanel_login" },
    { sort: 1, name: "注册", value: "openpanel_register" },
    { sort: 1, name: "邮箱", value: "openpanel_mail" },
    { sort: 1, name: "官方邮箱", value: "openpanel_official_mail" },
    { sort: 1, name: "兑换", value: "openpanel_excharge" },
    { sort: 1, name: "活动", value: "openpanel_activity" },
    { sort: 1, name: "奖励记录", value: "openpanel_record_mine" },
    { sort: 1, name: "奖励记录详情", value: "openpanel_record_mine_detail" },
    { sort: 1, name: "我的直属", value: "openpanel_directly" },
    { sort: 1, name: "google验证", value: "openpanel_google_verification" },
    { sort: 1, name: "我的钱包", value: "openpanel_wallet" },
    { sort: 1, name: "业绩查询", value: "openpanel_performance" },
    { sort: 1, name: "设置保底", value: "openpanel_promotion_floor" },
    { sort: 1, name: "质押", value: "openpanel_pledge" },
    { sort: 1, name: "质押记录", value: "openpanel_pledge_records" },
    { sort: 1, name: "解除质押", value: "openpanel_pledge_unstaking" },
    { sort: 1, name: "交换记录", value: "openpanel_swap_record" },
    { sort: 1, name: "奖励排行榜", value: "openpanel_bonus_ranking" },
    { sort: 1, name: "服务条款", value: "openpanel_service" },
    { sort: 1, name: "联系我们", value: "openpanel_contract" },
    { sort: 1, name: "用户中心", value: "openpanel_user_center" },
    { sort: 1, name: "用户认证", value: "openpanel_plat_users_verification" },
    { sort: 1, name: "设置真实姓名", value: "openpanel_real_name" },
    { sort: 1, name: "设置CPF", value: "openpanel_set_cpf" },
    { sort: 1, name: "设置昵称", value: "openpanel_nick_name" },
    { sort: 1, name: "安全中心", value: "openpanel_safety_center" },
    { sort: 1, name: "绑定邮箱", value: "openpanel_safety_center_email" },
    { sort: 1, name: "绑定手机", value: "openpanel_safety_center_phone" },
    { sort: 1, name: "google设置", value: "openpanel_google_settings" },
    { sort: 1, name: "绑定google", value: "openpanel_bind_google" },
    { sort: 1, name: "设置交易密码", value: "openpanel_trade_password" },
    { sort: 1, name: "绑定邀请码", value: "openpanel_bind_invite" },
    { sort: 1, name: "游戏汇率", value: "openpanel_game_rate" },
    { sort: 1, name: "提款记录", value: "openpanel_record_exchange" },
    { sort: 1, name: "充值记录", value: "openpanel_record_recharge" },
    { sort: 1, name: "地址薄", value: "openpanel_address_book" },
    { sort: 1, name: "地址薄备注", value: "openpanel_address_book_remark" },
    { sort: 1, name: "订单中心", value: "openpanel_order" },
    { sort: 1, name: "代理管理", value: "openpanel_agent_manager" },
    { sort: 1, name: "添加用户-信用代理", value: "openpanel_directly_adduser" },
    { sort: 1, name: "信用统计", value: "openpanel_statistics_credit" },
    { sort: 1, name: "代理统计", value: "openpanel_promotion_statistics" },
    { sort: 1, name: "业绩详情", value: "openpanel_performance_detail" },
    { sort: 1, name: "审核流水", value: "openpanel_gold_waterl" },
    { sort: 1, name: "时区设置", value: "openpanel_timezone" },
    { sort: 1, name: "游戏大厅-体育", value: "opencasino_sports" },
    { sort: 1, name: "游戏大厅-真人", value: "opencasino_live_casino" },
    { sort: 1, name: "游戏大厅-区块链", value: "opencasino_blockchain_games" },
    { sort: 1, name: "游戏大厅-捕鱼", value: "opencasino_fishing_games" },
    { sort: 1, name: "游戏大厅-电子", value: "opencasino_slots_games" },
    { sort: 1, name: "游戏大厅-彩票", value: "opencasino_lottery_games" },
    { sort: 1, name: "游戏大厅-棋牌", value: "opencasino_cards_games" },
    { sort: 1, name: "每日签到", value: "openpanel_dailysign" },
    { sort: 1, name: "导航栏", value: "showNovigation" },
    { sort: 1, name: "每日任务", value: "openpanel_dailytask" },
    { sort: 1, name: "推广奖励", value: "openpanel_promotionreward" },
    { sort: 1, name: "自定义游戏", value: "openpanel_promotionreward" },
    { sort: 1, name: "彩球活动", value: "openpage_activity_slots" },
    { sort: 1, name: "转盘活动", value: "openpanel_spin_lottery" },
];
